### ISSUE TITLE
cache CA API/grafeas data for an image on each cron run

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#218]
Currently kritis scans each pod, pulling from the CA API each time on the cron job. It will be worthwhile to cache the results for a single img

**Comment by tstromberg** [comment]
As an operator, I would like to an alert within 5 minutes of a critical remote vulnerability being discovered on a pod that's running my corporate mail server so that I can decide whether or not to take it offline. Perhaps relying on the cron run isn't the intent, however. 

I'm curious why you feel this change would be worthwhile? The API is already likely caching data, so I'm not yet convinced that adding our own caching layer will add as much value as it would complexity. It would help to see measured empirical evidence that not caching this data within kritis will be harmful for customers.

**Comment by tejal29** [comment]
Right now,  the cron job runs through all pods and then fetch all images.

If there are 2 pods running same images, we would make a call to CA twice for the same image.
The idea here is to speed up cron processing for such cases which will show for big clusters.
However, we only want to cache results for the current run. 

The next run, we would want to get the new/updated set of  vuln.

**Comment by tstromberg** [comment]
OK. Caching within a single run makes great sense. Thanks for clarifying!

**Comment by tstromberg** [comment]
Can this be closed now?

**Comment by aaron-prindle** [comment]
fixed with #242, closing
