### ISSUE TITLE
Kritis leaks memory

### ISSUE THREAD

**Issue by klauern** [grafeas/kritis#391]
## Expected Behavior
It runs at a stable memory footprint

## Actual Behavior
it doesn't?

## Steps to Reproduce the Problem
Run it for a while

## Additional info

I don't know how to better debug the issue, but here's a graph:
![image](https://user-images.githubusercontent.com/4735/63433240-6c668d80-c3e8-11e9-8b06-49ac32f0e9a1.png)

Each of these is an individual container on a separate Kubernetes cluster, so they are similar in nature but will have their own footprint.

I'd appreciate any guidance on what I can do to better provide information on what is going on.  This is my only window into the view that I can find, and I'm scratching my head to find other ways to get this information on a running cluster.

**Comment by klauern** [comment]
Note that the one that looks the most stable is our least-used server, so it doesn't get any traffic, hence it doesn't really fluctuate.

**Comment by ooq** [comment]
Hi @klauern , can you describe the workload a little bit?

**Comment by vbanthia** [comment]
We also faced the same issue and I did some profiling and found out memory leak is because of grafeasclient connections are not closed once the request is handled properly. 

I created debug docker image with netstat installed and observe new grpc connections (TCP) getting created whenever a new pod is created. These connections do not get closed and left open. 

```console
root@kritis-validation-hook-f76fd4c75-z2cvg:/go# netstat -W | wc -l
524
```

**Connections**
```
tcp        0      0 kritis-validation-hook-f76fd4c75-z2cvg:55436 nrt12s23-in-f10.1e100.net:https ESTABLISHED
tcp        0      0 kritis-validation-hook-f76fd4c75-z2cvg:44904 nrt12s13-in-f10.1e100.net:https ESTABLISHED
tcp        0      0 kritis-validation-hook-f76fd4c75-z2cvg:54140 nrt12s15-in-f74.1e100.net:https ESTABLISHED
```

We internally use kritis fork and temporary using this fix. 
https://github.com/mercari/kritis/pull/18


Ideally, Kritis should not create grafeasclient inside handler but instead should be initialized before calling request handler so that same connection can be reused between goroutines (request handlers)

(https://github.com/grafeas/kritis/blob/681e6d3e8a4675d386e580fd643304c5e0263245/pkg/kritis/admission/admission.go#L246)

**Comment by aysylu** [comment]
Thank you @klauern for reporting the issue and @vbanthia for contributing a potential fix! I'd be happy to review a PR with the fix, merge and release it as `0.1.1`.

**Comment by vbanthia** [comment]
Wrote a PR to fix this issue. https://github.com/grafeas/kritis/pull/394

**Comment by klauern** [comment]
We will be testing this out in the next week on our internal tools K8s cluster.  We should be able to tell fairly quickly if this is fixed.

**Comment by aysylu** [comment]
Great, thanks for the update! Looking forward to hearing from you.

**Comment by aysylu** [comment]
@klauern have you been able to confirm this by any chance?

**Comment by aysylu** [comment]
Marking this resolved due to inactivity. Please re-open if this is still an issue.
