### ISSUE TITLE
GRPC Errors from webhook to Grafeas

### ISSUE THREAD

**Issue by judavi** [grafeas/kritis#465]
Hello Kritis Team!
I have been playing with the latest version of Grafeas/Kritis and I'm building Kritis from the source.
My Grafeas installation, in particular, is behind an Nginx proxy (this also helps me to get an idea of what Kritis requests are being executed) and I notice something in particular:

Kritis webhook log:
Kritis is trying to get the Vulnz from Grafeas but is not able to complete the transaction:
![Capture](https://user-images.githubusercontent.com/1766933/74244785-dd249d80-4cd9-11ea-97d9-4d5e9afe23e8.png)

For some reason, the GRPC connection is established but also looks like is dropped all the time?
I'm able to see something strange is happening on the proxy side because the Grafeas server is flooded by many posts to ListOcurrences 

![image](https://user-images.githubusercontent.com/1766933/74244881-080ef180-4cda-11ea-8f82-c252b08485b0.png)

I'm already using the "GRPC debugging toolkit" : GRPC_GO_LOG_VERBOSITY_LEVEL = 99, GRPC_GO_LOG_SEVERITY_LEVEL = info, GRPC_VERBOSITY = go

Any suggestion of what else I could try? Thanks!

**Comment by judavi** [comment]
I think I have found the issue (it's an error on my Oracle DB implementation and the pagination token) but also that made me realize about a small change on:
https://github.com/grafeas/kritis/blob/588f70e090ad2ee4c98e65a6d105976ade4aabb2/pkg/kritis/metadata/grafeas/grafeas.go#L244
I'm wondering if instead of evaluating 
```
len(occs) == 0 
````
it should be 
```
len(resp.0ccurrences) == 0
```
The reason is that if the response is empty it's not necessary to iterate anymore. And occs is appending the results on each iteration
What do you think?
https://github.com/grafeas/kritis/blob/588f70e090ad2ee4c98e65a6d105976ade4aabb2/pkg/kritis/metadata/grafeas/grafeas.go#L242

**Comment by aysylu** [comment]
Hi @judavi, glad to hear you found and resolved the issue on the OracleDB side! As you pointed out, `resp.Occurrences` is already appended to `occs`, so on the first iteration of the loop, if no occurrences are found, this will exit the loop, so it's functionally equivalent. However, as we're iterating over all the paged occurrences, `occs` will no longer be empty even if `resp.Occurrences` are returned empty (which may happen, see [pagination API approach](https://developers.google.com/calendar/v3/pagination)), so the only way to get all the results would be to check the list of occurrences gathered so far *AND* the `nextPageToken`. Does this make sense?

I'm closing the issue since the original question is resolved, but feel free to respond on this thread if there's anything else.
