### ISSUE TITLE
about 1) “ALL attestation authorities to be satisfied” ,  why not “any attestation authority to be satisfied” ?

### ISSUE THREAD

**Issue by liufangwai** [grafeas/kritis#588]
**Is your feature request related to a problem? Please describe.**
No.  GenericAttestationPolicy (GAP) is a Custom Resource Definition which enforces policies based on pre-existing attestations. The policy expects either 1) ALL attestation authorities to be satisfied, or 2) the image url matches one of the allow-listed name patterns (see exact matching behavior at the pattern spec section below), before allowing the container image to be admitted. 
about 1) “ALL attestation authorities to be satisfied” ,  why not “any attestation authority to be satisfied” ?

**Describe the solution you'd like**
Usually one container image have one attestation, why we require "ALL attestation authorities to be satisfied"? Instead, is "any attestation authority is to be satisfied" better ?

**Describe alternatives you've considered**
Usually one container image have one attestation, why we require "ALL attestation authorities to be satisfied"? Instead, is "any attestation authority is to be satisfied" better ?

**Additional context**
No

**Comment by nenaddedic** [comment]
Instead of answering "which semantics is better", let me offer a workaround and see if that helps.

An AttestationAuthority (AA) can specify multiple public keys.  Signature verification follows the "any key" semantics.  So, for example, if your AA has PK1 and PK2, then this AA will verify an attestation as long as it has a signature verifiable by PK1 **or** PK2.

Can you make use of this to accomplish your goal?
